In [6]:
import yfinance as yf
import datetime
import pandas as pd
import numpy as np

In [10]:
from ta import add_all_ta_features

In [12]:
df = yf.download('AAPL',start='2022-01-01')

[*********************100%%**********************]  1 of 1 completed

In [14]:
all_data = add_all_ta_features(
        df,
        open="Open",
        high="High",
        low="Low",
        close="Close",
        volume="Volume")

/Users/rhcproc/Documents/GitHub/pazer/notebook/venv/lib/python3.9/site-packages/ta/trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

In [22]:
all_data.head()

,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2022-01-03,177.830002,182.880005,177.710007,182.009995,179.953903,104487900,6.932133e+07,104487900,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2022-01-04,182.630005,182.940002,179.119995,179.699997,177.669998,99310400,1.680499e+05,5177500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.269160,-1.277282,-1.269160
2022-01-05,179.610001,180.169998,174.639999,174.919998,172.944000,94537600,-8.479616e+07,-89360100,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.659988,-2.696006,-3.895388
2022-01-06,172.699997,175.300003,171.639999,172.000000,170.056961,96904000,-1.626371e+08,-186264100,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.669334,-1.683424,-5.499695
2022-01-07,172.889999,174.139999,171.029999,172.169998,170.225067,86709100,-1.857781e+08,-99555000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.098836,0.098787,-5.406295

In [18]:
nan_features = []
for x in all_data.iloc[-1].index:
    if pd.isnull(all_data.iloc[-1][x]):
        nan_features.append(x)

In [20]:
nan_features

['trend_psar_down']